# My Alacritty Config
# Scott Rice
# Started: 2023-12-06
# Updated: 2024-01-09

[window.padding]
    x= 16
    y= 0

[window]
  opacity= 0.8
  startup_mode= "Maximized"
  title= "Alacritty"
  dynamic_title= true

[scrolling]
  history= 10000
  multiplier= 3

[font]
    size= 12.0

[font.normal]
    family= "monospace"

[colors.primary]
    background= '#000000'
